App/urls.py
from django.urls import path

from.import views

app_name ='App'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('contact/', views.contact, name='contact' ),
    path('services/', views.service, name = 'service'),
    path('about/', views.about, name = 'about'),
    path('cars/', views.cars, name = 'cars'),
    path('blog/', views.blog, name = 'blog'),
    path('enterdetails', views.enterdetails, name = 'enterdetails')
]

CarHire/urls.py
from django.contrib import admin

from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App.urls')),
]

App/models.py
from django.db import models

# Create your models here.

class Client(models.Model):
    fname = models.CharField(max_length=20, blank=False)
    lname = models.CharField(max_length=20, blank=False)
    email = models.EmailField()
    message = models.TextField(default="decsription")

    def __str__ (self):
        return self.lname


class Trip(models.Model):
    pickup = models.CharField(max_length=10)
    dropoff = models.CharField(max_length=20)
    start = models.DateField()
    end = models.DateField()

    def __str__(self):
        return self.pickup

App/views.py
from django.shortcuts import render, redirect

from django.http import HttpResponse

from django.contrib import messages

from. models import Client, Trip

# Create your views here.

def index(request):
    context = {'link' : 'index'}
    return render(request, 'index.html', context)

def contact(request):
    return render(request, 'contact.html', {'link' : 'contact'})

def service(request):
    return render(request, 'services.html')

def  about(request):
    return render(request, 'about.html')

def  cars(request):
    return render(request, 'cars.html')

def  blog(request):
    return render(request, 'blog.html')


def enterdetails(request):
    if request.method == 'POST':
        fname = request.POST.get('fname')
        lname = request.POST.get('lname')
        email = request.POST.get('email')
        message = request.POST.get('message')

        client = Client(fname =fname, lname=lname, email=email, message=message)
        client.save()
        messages.success(request, 'Successfully Saved!')
        return redirect('/contact')



    return redirect('/contact')

App/templates/cars.html
{% extends 'master.html' %}

{% load static %}

{% block title %} More Cars &mdash; {% endblock %}

{% block content %}
    <div class="ftco-blocks-cover-1">
      <div class="ftco-cover-1 overlay innerpage" style="background-image: url({% static 'images/hero_2.jpg' %})">
        <div class="container">
          <div class="row align-items-center justify-content-center">
            <div class="col-lg-6 text-center">
              <h2> Cars Available for Hire are Listed Below</h2>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="site-section bg-light">
      <div class="container">
        <div class="row">
          <div class="col-lg-4 col-md-6 mb-4">
            <div class="item-1">
                <a href="#"><img src="{% static 'images/img_1.jpg' %}" alt="Image" class="img-fluid"></a>
                <div class="item-1-contents">
                  <div class="text-center">
                  <h3><a href="#">Range Rover S64 Coupe</a></h3>
                  <div class="rating">
                    <span class="icon-star text-warning"></span>
                    <span class="icon-star text-warning"></span>
                    <span class="icon-star text-warning"></span>
                    <span class="icon-star text-warning"></span>
                    <span class="icon-star text-warning"></span>
                  </div>
                  <div class="rent-price"><span>kes2500/</span>day</div>
                  </div>
                  <ul class="specs">
                    <li>
                      <span>Doors</span>
                      <span class="spec">4</span>
                    </li>
                    <li>
                      <span>Seats</span>
                      <span class="spec">5</span>
                    </li>
                    <li>
                      <span>Transmission</span>
                      <span class="spec">Automatic</span>
                    </li>
                    <!-- <li>
                      <span>Minium age</span>
                      <span class="spec">18 years</span>
                    </li> -->
                  </ul>
                  <div class="d-flex action">
                    <a href="{% url 'App:contact' %}" class="btn btn-success">Rent Now</a>
                  </div>
                </div>
              </div>
          </div>

          <div class="col-lg-4 col-md-6 mb-4">
            <div class="item-1">
                <a href="#"><img src="{% static 'images/img_2.jpg' %}" alt="Image" class="img-fluid"></a>
                <div class="item-1-contents">
                  <div class="text-center">
                  <h3><a href="#">Range Rover S64 Coupe</a></h3>
                  <div class="rating">
                    <span class="icon-star text-warning"></span>
                    <span class="icon-star text-warning"></span>
                    <span class="icon-star text-warning"></span>
                    <span class="icon-star text-warning"></span>
                    <span class="icon-star text-warning"></span>
                  </div>
                  <div class="rent-price"><span>kes1500/</span>day</div>
                  </div>
                  <ul class="specs">
                    <li>
                      <span>Doors</span>
                      <span class="spec">4</span>
                    </li>
                    <li>
                      <span>Seats</span>
                      <span class="spec">5</span>
                    </li>
                    <li>
                      <span>Transmission</span>
                      <span class="spec">Automatic</span>
                    </li>
                    <!-- <li>
                      <span>Minium age</span>
                      <span class="spec">18 years</span>
                    </li> -->
                  </ul>
                  <div class="d-flex action">
                    <a href="{% url 'App:contact' %}" class="btn btn-success">Hire Now</a>
                  </div>
                </div>
              </div>
          </div>


          <div class="col-lg-4 col-md-6 mb-4">
            <div class="item-1">
                <a href="#"><img src="{% static 'images/img_3.jpg' %}" alt="Image" class="img-fluid"></a>
                <div class="item-1-contents">
                  <div class="text-center">
                  <h3><a href="#">Range Rover S64 Coupe</a></h3>
                  <div class="rating">
                    <span class="icon-star text-warning"></span>
                    <span class="icon-star text-warning"></span>
                    <span class="icon-star text-warning"></span>
                    <span class="icon-star text-warning"></span>
                    <span class="icon-star text-warning"></span>
                  </div>
                  <div class="rent-price"><span>kes2500/</span>day</div>
                  </div>
                  <ul class="specs">
                    <li>
                      <span>Doors</span>
                      <span class="spec">4</span>
                    </li>
                    <li>
                      <span>Seats</span>
                      <span class="spec">5</span>
                    </li>
                    <li>
                      <span>Transmission</span>
                      <span class="spec">Automatic</span>
                    </li>
                    <!-- <li>
                      <span>Minium age</span>
                      <span class="spec">18 years</span>
                    </li> -->
                  </ul>
                  <div class="d-flex action">
                    <a href="{% url 'App:contact' %}" class="btn btn-success">Hire Now</a>
                  </div>
                </div>
              </div>
          </div>

          <div class="col-lg-4 col-md-6 mb-4">
            <div class="item-1">
                <a href="#"><img src="{% static 'images/img_1.jpg' %}" alt="Image" class="img-fluid"></a>
                <div class="item-1-contents">
                  <div class="text-center">
                  <h3><a href="#">Range Rover S64 Coupe</a></h3>
                  <div class="rating">
                    <span class="icon-star text-warning"></span>
                    <span class="icon-star text-warning"></span>
                    <span class="icon-star text-warning"></span>
                    <span class="icon-star text-warning"></span>
                    <span class="icon-star text-warning"></span>
                  </div>
                  <div class="rent-price"><span>kes2500/</span>day</div>
                  </div>
                  <ul class="specs">
                    <li>
                      <span>Doors</span>
                      <span class="spec">4</span>
                    </li>
                    <li>
                      <span>Seats</span>
                      <span class="spec">5</span>
                    </li>
                    <li>
                      <span>Transmission</span>
                      <span class="spec">Automatic</span>
                    </li>
                    <li>
                      <span>Minium age</span>
                      <span class="spec">18 years</span>
                    </li>
                  </ul>
                  <div class="d-flex action">
                    <a href="{% url 'App:contact' %}" class="btn btn-success">Hire Now</a>
                  </div>
                </div>
              </div>
          </div>

          <div class="col-lg-4 col-md-6 mb-4">
            <div class="item-1">
                <a href="#"><img src="{% static 'images/img_2.jpg' %}" alt="Image" class="img-fluid"></a>
                <div class="item-1-contents">
                  <div class="text-center">
                  <h3><a href="#">Range Rover S64 Coupe</a></h3>
                  <div class="rating">
                    <span class="icon-star text-warning"></span>
                    <span class="icon-star text-warning"></span>
                    <span class="icon-star text-warning"></span>
                    <span class="icon-star text-warning"></span>
                    <span class="icon-star text-warning"></span>
                  </div>
                  <div class="rent-price"><span>kes2100/</span>day</div>
                  </div>
                  <ul class="specs">
                    <li>
                      <span>Doors</span>
                      <span class="spec">4</span>
                    </li>
                    <li>
                      <span>Seats</span>
                      <span class="spec">5</span>
                    </li>
                    <li>
                      <span>Transmission</span>
                      <span class="spec">Automatic</span>
                    </li>
                    <li>
                      <span>Minium age</span>
                      <span class="spec">18 years</span>
                    </li>
                  </ul>
                  <div class="d-flex action">
                    <a href="{% url 'App:contact' %}" class="btn btn-success">Hire Now</a>
                  </div>
                </div>
              </div>
          </div>


          <div class="col-lg-4 col-md-6 mb-4">
            <div class="item-1">
                <a href="#"><img src="{% static 'images/img_3.jpg' %}" alt="Image" class="img-fluid"></a>
                <div class="item-1-contents">
                  <div class="text-center">
                  <h3><a href="#">Range Rover S64 Coupe</a></h3>
                  <div class="rating">
                    <span class="icon-star text-warning"></span>
                    <span class="icon-star text-warning"></span>
                    <span class="icon-star text-warning"></span>
                    <span class="icon-star text-warning"></span>
                    <span class="icon-star text-warning"></span>
                  </div>
                  <div class="rent-price"><span>kes2500/</span>day</div>
                  </div>
                  <ul class="specs">
                    <li>
                      <span>Doors</span>
                      <span class="spec">4</span>
                    </li>
                    <li>
                      <span>Seats</span>
                      <span class="spec">5</span>
                    </li>
                    <li>
                      <span>Transmission</span>
                      <span class="spec">Automatic</span>
                    </li>
                    <li>
                      <span>Minium age</span>
                      <span class="spec">18 years</span>
                    </li>
                  </ul>
                  <div class="d-flex action">
                    <a href="{% url 'App:contact' %}" class="btn btn-success">Hire Now</a>
                  </div>
                </div>
              </div>
          </div>


          <div class="col-12">
            <span class="p-3">1</span>
            <a href="#" class="p-3">2</a>
            <a href="#" class="p-3">3</a>
            <a href="#" class="p-3">4</a>
          </div>
        </div>
      </div>
    </div>

    <div class="container site-section mb-5">
      <div class="row justify-content-center text-center">
        <div class="col-7 text-center mb-5">
          <h2>How it works</h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo assumenda, dolorum necessitatibus eius earum voluptates sed!</p>
        </div>
      </div>
      <div class="how-it-works d-flex">
        <div class="step">
          <span class="number"><span>01</span></span>
          <span class="caption">Time &amp; Place</span>
        </div>
        <div class="step">
          <span class="number"><span>02</span></span>
          <span class="caption">Car</span>
        </div>
        <div class="step">
          <span class="number"><span>03</span></span>
          <span class="caption">Details</span>
        </div>
        <div class="step">
          <span class="number"><span>04</span></span>
          <span class="caption">Checkout</span>
        </div>
        <div class="step">
          <span class="number"><span>05</span></span>
          <span class="caption">Done</span>
        </div>

      </div>
    </div>

{% endblock %}   

App/templates/contact.html
{% extends 'master.html' %}

{% load static %}

{% block title %} Contact Us &mdash; {% endblock %}

{% block content %}



    <div class="ftco-blocks-cover-1" >
      <div class="contact-overlay ftco-cover-1 overlay innerpage" style="background-image: url({% static 'images/hero_2.jpg' %})" >
        <div class="container">
          <div class="row align-items-center justify-content-center">
            <div class="col-lg-6 text-center">
              <h1>Hiring a car Made Simple</h1><br>
              <!-- <a href="{% url 'App:contact' %}" class="ml-auto btn btn-warning">Hire Now</a> -->
            </div>
          </div>
        </div>
      </div>
    </div>


    <!-- Start oc contact form Section -->
    <div class="site-section bg-light" id="contact-section">
      <div class="container">
        <div class="row justify-content-center text-center">
        <div class="col-7 text-center mb-5">
          <h4>Contact Us  To Hire A Car</h4>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo assumenda, dolorum necessitatibus eius earum voluptates sed!</p>
        </div>
      </div>

{% for dd in messages%}
  <h3>{{dd}}</h3> 
{% endfor %}  

        <div class="row">
          <div class="col-lg-8 mb-5" >
            <form action="/enterdetails" method="post" enctype="multipart/form-data">
              {% csrf_token %}
              <div class="form-group row">
                <div class="col-md-6 mb-4 mb-lg-0">
                  <input type="text" class="form-control" placeholder="First name" name="fname">
                </div>
                <div class="col-md-6">
                  <input type="text" class="form-control" placeholder="Last name" name="lname">
                </div>
              </div>

              <div class="form-group row">
                <div class="col-md-12">
                  <input type="text" class="form-control" placeholder="Email address" name="email">
                </div>
              </div>
              <div class="form-group row">
                <div class="col-md-12 mr-auto">
                  <label for="country">Select type of a Car</label>
                    <select class="form-control" id="car" name="Car Type">
                      <option value="australia">Range Rover</option>
                      <option value="canada">Audi</option>
                     <option value="usa">Ford</option>
                     <option value="usa">Mazda </option>
                     <option value="usa">Tesla </option>
                     <option value="usa">Porche</option>
                    </select>
                </div>
              </div>


              <div class="form-group row">
                <div class="col-md-12">
                  <textarea name="message" id="" class="form-control" placeholder="Write your message.(optional)" cols="30" rows="4"></textarea>
                </div>
              </div>
              <div class="form-group row">
                <div class="col-md-12 mr-auto">
                  <input type="submit" class=" btn btn-block btn-success text-white py-2 px-5" value="Send ">
                </div>
              </div>
            </form>
          </div>
          <div class="col-lg-4 ml-auto">
            <div class="bg-white p-3 p-md-4">
              <h3 class="text-black mb-2">Contact Info</h3>
              <ul class="list-unstyled footer-link">
                <li class="d-block mb-2">
                  <span class="d-block text-black">Address:</span>
                  <span>34th Street , Nakuru City, Kenya</span></li>
                <li class="d-block mb-2"><span class="d-block text-black">Phone:</span><span>+254 00 4002 000</span></li>
                <li class="d-block mb-2"><span class="d-block text-black">Email:</span><span>cars@gmail.com</span></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>

    {% endblock %}
    

    

App/templates/master.html
{% load static %}

<!doctype html>
<html lang="en">

  <head>
    <title>{% block title %}Hire A Car &mdash; {% endblock  %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=DM+Sans:300,400,700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{%static 'fonts/icomoon/style.css' %}">

    <link rel="stylesheet" href="{%static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{%static 'css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{%static 'css/jquery.fancybox.min.css' %}">
    <link rel="stylesheet" href="{%static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{%static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{%static 'fonts/flaticon/font/flaticon.css' %}">
    <link rel="stylesheet" href="{%static 'css/aos.css' %}">

    <!-- MAIN CSS -->
    <link rel="stylesheet" href="{%static 'css/style.css' %}">

  </head>

  <body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">

    
    <div class="site-wrap" id="home-section">

      <div class="site-mobile-menu site-navbar-target">
        <div class="site-mobile-menu-header">
          <div class="site-mobile-menu-close mt-3">
            <span class="icon-close2 js-menu-toggle"></span>
          </div>
        </div>
        <div class="site-mobile-menu-body"></div>
      </div>



      <header class="site-navbar site-navbar-target" role="banner">

        <div class="container">
          <div class="row align-items-center position-relative">

            <div class="col-3 ">
              <div class="site-logo">
                <a class="{% if link ==  'index' %} index {% endif %}" href="/">CarHire ||.</a>
              </div>
            </div>

            <div class="col-9  text-right">
              

              <span class="d-inline-block d-lg-none">
                <a href="#" class="text-white site-menu-toggle js-menu-toggle py-5 text-white"><span class="icon-menu h3 text-white"></span></a></span>

              

              <nav class="site-navigation text-right ml-auto d-none d-lg-block" role="navigation">
                <ul class="site-menu main-menu js-clone-nav ml-auto ">
                  <li class=""><a href="{% url 'App:index' %}" class="nav-link">Home</a></li>
                  <li><a href="{% url 'App:service' %}" class="nav-link">Services</a></li>
                  <li><a href="{% url 'App:cars' %}" class="nav-link">Cars</a></li>
                  <li><a href="{% url 'App:about' %}" class="nav-link">About Us</a></li>
                  <li><a href="{% url 'App:blog' %}" class="nav-link">Blog</a></li>
                  <li><a href="{% url 'App:contact' %}" class="nav-link">Contact</a></li>
                </ul>
              </nav>
            </div>

            
          </div>
        </div>

      </header>


      {% block content %}

      {% endblock %}


      <footer class="site-footer">
        <div class="container">
          <div class="row">
            <div class="col-lg-3">
              <h2 class="footer-heading mb-2">About Us</h2>
                  <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. </p>
            </div>
            <div class="col-lg-8 ml-auto">
              <div class="row">
                <div class="col-lg-3">
                  <h2 class="footer-heading mb-2">Quick Links</h2>
                  <ul class="list-unstyled">
                    <li><a href="{% url 'App:about' %}">About Us</a></li>
                    <li><a href="#">Testimonials</a></li>
                    <li><a href="#">Terms of Service</a></li>
                    <li><a href="#">Privacy</a></li>
                    <li><a href="{% url 'App:contact' %}">Contact Us</a></li>
                  </ul>
                </div>
                <div class="col-lg-3">
                  <h2 class="footer-heading mb-2">Quick Links</h2>
                  <ul class="list-unstyled">
                    <li><a href="#">About Us</a></li>
                    <li><a href="#">Testimonials</a></li>
                    <li><a href="#">Terms of Service</a></li>
                    <li><a href="#">Privacy</a></li>
                    <li><a href="#">Contact Us</a></li>
                  </ul>
                </div>
                <div class="col-lg-3">
                  <h2 class="footer-heading mb-2">Quick Links</h2>
                  <ul class="list-unstyled">
                    <li><a href="#">About Us</a></li>
                    <li><a href="#">Testimonials</a></li>
                    <li><a href="#">Terms of Service</a></li>
                    <li><a href="#">Privacy</a></li>
                    <li><a href="#">Contact Us</a></li>
                  </ul>
                </div>
                <div class="col-lg-3">
                  <h2 class="footer-heading mb-2">Quick Links</h2>
                  <ul class="list-unstyled">
                    <li><a href="#">About Us</a></li>
                    <li><a href="#">Testimonials</a></li>
                    <li><a href="#">Terms of Service</a></li>
                    <li><a href="#">Privacy</a></li>
                    <li><a href="#">Contact Us</a></li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <div class="row pt-5 mt-2 text-center">
            <div class="col-md-12">
              <div class="border-top pt-3 mb-2">
                <p>
              <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
              Copyright &copy;<script>document.write(new Date().getFullYear());</script> 
              All rights reserved | This Website was created <br> 
              <!-- <i class="icon-heart text-danger" aria-hidden="true"></i>  -->
              and managed by <a href="#" target="_blank" >MigObare</a> Tech
              <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
              </p>
              </div>
            </div>
  
          </div>
        </div>
      </footer>
  
      </div>
  
      <script src="{%static 'js/jquery-3.3.1.min.js' %}"></script>
      <script src="{%static 'js/popper.min.js' %}"></script>
      <script src="{%static 'js/bootstrap.min.js' %}"></script>
      <script src="{%static 'js/owl.carousel.min.js' %}"></script>
      <script src="{%static 'js/jquery.sticky.js' %}"></script>
      <script src="{%static 'js/jquery.waypoints.min.js' %}"></script>
      <script src="{%static 'js/jquery.animateNumber.min.js' %}"></script>
      <script src="{%static 'js/jquery.fancybox.min.js' %}"></script>
      <script src="{%static 'js/jquery.easing.1.3.js' %}"></script>
      <script src="{%static 'js/bootstrap-datepicker.min.js' %}"></script>
      <script src="{%static 'js/aos.js' %}"></script>
  
      <script src="{%static 'js/main.js' %}"></script>
  
    </body>
  
  </html>
  

App/templates/services.html
{% extends 'master.html' %}

{% load static %}

{% block title %} Services Offered &mdash;{% endblock %}

{% block content %}
    <div class="ftco-blocks-cover-1">
      <div class="ftco-cover-1 overlay innerpage" style="background-image: url({% static 'images/hero_2.jpg' %})">
        <div class="container">
          <div class="row align-items-center justify-content-center">
            <div class="col-lg-6 text-center">
              <h2>Our Services</h2>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="site-section">
      <div class="container">
        <div class="row">
          <div class="col-lg-4 mb-4 mb-lg-5">
            <div class="service-1 dark">
              <span class="service-1-icon">
                <span class="flaticon-car"></span>
              </span>
              <div class="service-1-contents">
                <h3>Car Key</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati, laboriosam.</p>
              </div>
            </div>
          </div>
          <div class="col-lg-4 mb-4 mb-lg-5">
            <div class="service-1 dark">
              <span class="service-1-icon">
                <span class="flaticon-valet-1"></span>
              </span>
              <div class="service-1-contents">
                <h3>Car Key</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati, laboriosam.</p>
              </div>
            </div>
          </div>
          <div class="col-lg-4 mb-4 mb-lg-5">
            <div class="service-1 dark">
              <span class="service-1-icon">
                <span class="flaticon-key"></span>
              </span>
              <div class="service-1-contents">
                <h3>Car Key</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati, laboriosam.</p>
              </div>
            </div>
          </div>
          <div class="col-lg-4 mb-4 mb-lg-5">
            <div class="service-1 dark">
              <span class="service-1-icon">
                <span class="flaticon-car-1"></span>
              </span>
              <div class="service-1-contents">
                <h3>Repair</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati, laboriosam.</p>
              </div>
            </div>
          </div>
          <div class="col-lg-4 mb-4 mb-lg-5">
            <div class="service-1 dark">
              <span class="service-1-icon">
                <span class="flaticon-traffic"></span>
              </span>
              <div class="service-1-contents">
                <h3>Car Accessories</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati, laboriosam.</p>
              </div>
            </div>
          </div>
          <div class="col-lg-4 mb-4 mb-lg-5">
            <div class="service-1 dark">
              <span class="service-1-icon">
                <span class="flaticon-valet"></span>
              </span>
              <div class="service-1-contents">
                <h3>Own a Car</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Obcaecati, laboriosam.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="container site-section mb-5">
      <div class="row justify-content-center text-center">
        <div class="col-7 text-center mb-5">
          <h2>How it works</h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo assumenda, dolorum necessitatibus eius earum voluptates sed!</p>
        </div>
      </div>
      <div class="how-it-works d-flex">
        <div class="step">
          <span class="number"><span>01</span></span>
          <span class="caption">Time &amp; Place</span>
        </div>
        <div class="step">
          <span class="number"><span>02</span></span>
          <span class="caption">Car</span>
        </div>
        <div class="step">
          <span class="number"><span>03</span></span>
          <span class="caption">Details</span>
        </div>
        <div class="step">
          <span class="number"><span>04</span></span>
          <span class="caption">Checkout</span>
        </div>
        <div class="step">
          <span class="number"><span>05</span></span>
          <span class="caption">Done</span>
        </div>

      </div>
    </div>
    {% endblock %}
    

    